// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt_zgV1qI-IcL76nBy7f47g1MQPgauCM8',
    appId: '1:867758047651:web:1d1954d837216adb5bda16',
    messagingSenderId: '867758047651',
    projectId: 'personal-planner-c86bb',
    authDomain: 'personal-planner-c86bb.firebaseapp.com',
    storageBucket: 'personal-planner-c86bb.firebasestorage.app',
    measurementId: 'G-WVGBGTL1VG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMlzAQ5iGj2UR9buqCnBoLfYepi5ywtM8',
    appId: '1:867758047651:android:a89090c9c6a3a94a5bda16',
    messagingSenderId: '867758047651',
    projectId: 'personal-planner-c86bb',
    storageBucket: 'personal-planner-c86bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa-YM6Z1OOw5aY-PK3hNot7M3YL4d9LmA',
    appId: '1:867758047651:ios:57fb2f55ca2774ed5bda16',
    messagingSenderId: '867758047651',
    projectId: 'personal-planner-c86bb',
    storageBucket: 'personal-planner-c86bb.firebasestorage.app',
    iosBundleId: 'com.example.personalPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa-YM6Z1OOw5aY-PK3hNot7M3YL4d9LmA',
    appId: '1:867758047651:ios:57fb2f55ca2774ed5bda16',
    messagingSenderId: '867758047651',
    projectId: 'personal-planner-c86bb',
    storageBucket: 'personal-planner-c86bb.firebasestorage.app',
    iosBundleId: 'com.example.personalPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt_zgV1qI-IcL76nBy7f47g1MQPgauCM8',
    appId: '1:867758047651:web:8eb9bdeadce999f95bda16',
    messagingSenderId: '867758047651',
    projectId: 'personal-planner-c86bb',
    authDomain: 'personal-planner-c86bb.firebaseapp.com',
    storageBucket: 'personal-planner-c86bb.firebasestorage.app',
    measurementId: 'G-L0BV08SSL5',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCt_zgV1qI-IcL76nBy7f47g1MQPgauCM8',
    appId: '1:867758047651:web:8eb9bdeadce999f95bda16',
    messagingSenderId: '867758047651',
    projectId: 'personal-planner-c86bb',
    authDomain: 'personal-planner-c86bb.firebaseapp.com',
    storageBucket: 'personal-planner-c86bb.firebasestorage.app',
    measurementId: 'G-L0BV08SSL5',
  );
}
